# Generated by Django 4.2.4 on 2023-08-17 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veisle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100)),
                ('aprasymas', models.TextField()),
                ('vietove', models.CharField(max_length=100)),
                ('zeme', models.CharField(max_length=100)),
                ('iranga', models.CharField(max_length=100)),
                ('siltnamis_ar_laukas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Darzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plotas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pasodinimo_data', models.DateField()),
                ('sodinimas_is_seklu', models.BooleanField(default=False)),
                ('sodinuku_pikiavimas', models.DateField()),
                ('sodinuku_perkelimas_i_lysvas', models.DateTimeField()),
                ('tresimas', models.DateTimeField()),
                ('laistymas', models.DateTimeField()),
                ('purkimas', models.DateTimeField()),
                ('derliaus_nuemimas', models.DateTimeField()),
                ('pastabos', models.TextField()),
                ('vartotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('veisle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden_app.veisle')),
            ],
        ),
    ]
