# Generated by Django 4.2.4 on 2023-08-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veisle',
            name='iranga',
        ),
        migrations.RemoveField(
            model_name='veisle',
            name='vietove',
        ),
        migrations.RemoveField(
            model_name='veisle',
            name='zeme',
        ),
    ]
