# Generated by Django 4.2.4 on 2023-08-21 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garden_app', '0003_alter_veisle_siltnamis_ar_laukas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Darzo_darbai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasodinimo_data', models.DateField()),
                ('sodinimas_is_seklu', models.BooleanField(default=False)),
                ('sodinuku_pikiavimas', models.DateField()),
                ('sodinuku_perkelimas_i_lysvas', models.DateTimeField()),
                ('tresimas', models.DateTimeField()),
                ('laistymas', models.DateTimeField()),
                ('purkimas', models.DateTimeField()),
                ('derliaus_nuemimas', models.DateTimeField()),
                ('pastabos', models.TextField()),
                ('vartotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('veisle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden_app.veisle')),
            ],
        ),
        migrations.DeleteModel(
            name='Darzas',
        ),
    ]
