# Generated by Django 4.2.4 on 2023-08-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0004_darzo_darbai_delete_darzas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='darzo_darbai',
            options={'verbose_name': 'Daržo_darbas', 'verbose_name_plural': 'Daržo_darbai'},
        ),
        migrations.RenameField(
            model_name='darzo_darbai',
            old_name='purkimas',
            new_name='purskimas',
        ),
    ]
